server:
  port: 8084

# SDK 调用凭证
personalize:
  sdk-key: internal-sdk-key-2026

# RSA 私钥（与 mcp-sdk 内置公钥配对，解密全报文加密的 MCP 请求）
crypto:
  rsa:
    private-key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCueeEdf0JFS9y1DV5gb+FSuCzUzvcoj2IzA5BSXUEr0brM/uyDon104z+tf9ZUAhbBmYiq+H1ZcMljKFjXooVQj/PKLWFAqeK+tKpE5HO01ELv01t8dX98LlYQOjDclt2taS9wxuIutMejhqfM/mfIvUgc3/d2lG6vb2vuXsln4OU0fuxmybc/40Z8EK9Pf8HLL4xBxyCEX53QB4f6kifEOD3JlOVElby7SDSlcgT4tq2rcHieBIth4SxARIVcSbM8FqTpBGPqEWs1tPLZoqKZjsbZIKWr6ZBa2Ke4LXUQTvEydYrcbu8l0MKxmkiBKIHJUTFJhGM8z7k08kPj9cmbAgMBAAECggEAU9PkGFd9wCyQOH7ZUs0+PY+WnpJnxpmJTUhPjXsXplWIghiTCzXFQCU1AYeTst4kD9VUCA0GsLPTVmxarxP7KHdZYtCF0tsswYKs8hevDfkTxgVPBc+wNjpPCFHlCv8DN997NxyfLGCYMJWwRnoO5DApFxJ2Y4cyXODUQv1QmDL2IlPSZ5Xh/U7IX6ChFcIa6rJ+EvD+0wcnhZjV6NEJbez8S0h0CIy5zMdDFWKX2rzIHsR7is2/Pr7EKQBeOmyBTLnpWoV7AqJsIFw94+ryeCEZ+JU7eNI0acg5YiuW0jgpKGwJ1jk2s6r3ow6jn41JHYcKhQSMB1NWLngh5fiWrQKBgQDBuzqCrUKPDww2AxKYUYqp/0FpwkaPGbLaItZk7JFNcLv2SdmtGWKKaSm03C47wPh/1joHcqlkelh+U9U1yiaJTIzu7A9LAwnZjvQmLML+qV8p6zTuk6hq//Z/97a+PRj/BstHKEkNEhUg4ucxIQSYPt8KXO8g318ITV0MAUlOtwKBgQDmjkWhcRoJaY3iAltCosqzW4sBRTp2j/sCVHfWUg7FDstEPZkijwIm/LspS7qVK2Vj4dFWGPWINf6RdishBu8e2jLPfCjzlXfEjm/N590Yt0QMJzmS380JVqJfV83CpNP5T/HO5ykbezy9y6PvZMiLKau1oRK7fnVErk+mL+o4PQKBgAdClPbAt3XVAogjpVa/94pXXoQwG6TRObqjA5XUp71XNDQOoHG0OdUmC8ITXkgu+yEPTi1pRp/VVeumCJ9za+5JSB7MCeatvnjAurWTh9szTbWsctdeATnBTeONzPNkJsOn5YZNJC+xNcl9t1xH+HwcHw+sW+nHdTBCdfI1OiIRAoGBAJSa62Ktxfx/Hsaogi4nQ8Pro2NEPfShxUaxLzTjW0XEzVvE4GmYB+kdSX3KpA72E7oXmZiHKeuL8fPMWOxGzeXy+oEmJDctBi+ZJ5NueeIubhvvRHrY6g2025/ctnFZUJAH6XJVKPffrT0gfyAUs/aO+3Bsy+gyEGAegpQ5mhx5AoGBAMEloDW2c8fScCfPoX97ZgfCTFUNX4YEmCqqmwWTmn7f+4Mc11BlzwNDJPl4uPbrJIfRgyZKYgEGYzbfznqrvrieLrB49WHFgMjLHVDHOHdenEa69gkZvjqc8I/YSKhC871b9h6MC6s7M/L9vudpVkVpVonmtGx8dLC2V1b+LQP3

logging:
  level:
    org.springframework.web: INFO
